---
# tasks file for lb
#
- package: 
     name: 'haproxy'
     state: present
- template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        #  notify: "Restart Service"
- firewalld:
       port: 8080/tcp
       permanent: yes
       state: enabled
       immediate: yes
- service:
     name: 'haproxy'
     state: restarted


